version: "3"
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - /mosquitto/data:/mosquitto/data
      - /mosquitto/log:/mosquitto/log
    ports:
      - 1833:1833
      - 9001:9001
