package com.home.app.model;

// Layout.java

// Generated by https://quicktype.io

import java.util.Map;

public class Layout {
    private LayoutElement[] layouts;

    public LayoutElement[] getLayouts() {
        return layouts;
    }

    public void setLayouts(LayoutElement[] value) {
        this.layouts = value;
    }
}

// LayoutElement.java
